### ISSUE TITLE
Fail in Rails 6.1

### ISSUE THREAD

**Issue by foton** [samesystem/graphql_rails#172]
After upgrade to Rails 6.1 we getting error : 
```
 NameError:
rails_1     |        uninitialized constant ActionDispatch::Http::ParameterFilter
rails_1     |        Did you mean?  ActionDispatch::Http::Parameters
rails_1     |      # /data/bundles/base/ruby/2.7.0/gems/graphql_rails-1.1.0/lib/graphql_rails/controller/log_controller_action.rb:54:in `filtered_params'
rails_1     |      # /data/bundles/base/ruby/2.7.0/gems/graphql_rails-1.1.0/lib/graphql_rails/controller/log_controller_action.rb:40:in `default_payload
....
```
which comes from https://github.com/samesystem/graphql_rails/blob/master/lib/graphql_rails/controller/log_controller_action.rb#L54 .

I found this from previous Rails
```
ParameterFilter inherits from ActionDispatch::Http::ParameterFilter which will be removed from Rails 6.1:

DEPRECATION WARNING: ActionDispatch::Http::ParameterFilter is deprecated and will be removed from Rails 6.1. Use ActiveSupport::ParameterFilter instead.
```

**Comment by jusmat** [comment]
Hey, @foton ;) Could you cover this one with a simple spec, so we know we don't break the old way it used to work?

**Comment by foton** [comment]
Sure. I tested manually it on 6.0.3.4 and 6.1.

**Comment by foton** [comment]
@jusmat  Actually the spec is already [here](https://github.com/samesystem/graphql_rails/blob/master/spec/lib/graphql_rails/controller/log_controller_action_spec.rb#L51) (filtering out password). 

All You need is change Rails to 6.1 (to fail) . 
Fastest way: Change `graphql_rails.gemspec` , delete `Gemfile.lock` and run `bundle install`.
```
diff --git a/graphql_rails.gemspec b/graphql_rails.gemspec
index b3242dc..8b2ad52 100644
--- a/graphql_rails.gemspec
+++ b/graphql_rails.gemspec
@@ -21,12 +21,12 @@ Gem::Specification.new do |spec|
   spec.require_paths = ['lib']
 
   spec.add_dependency 'graphql', '~> 1.11', '>= 1.11.6'
-  spec.add_dependency 'activesupport', '>= 4'
+  spec.add_dependency 'activesupport', '>= 6.1'
 
   spec.add_development_dependency 'bundler', '~> 2'
   spec.add_development_dependency 'rake', '~> 13.0'
   spec.add_development_dependency 'rspec', '~> 3.0'
   spec.add_development_dependency 'activerecord'
   spec.add_development_dependency 'pry-byebug'
-  spec.add_development_dependency 'rails', '~> 6'
+  spec.add_development_dependency 'rails', '~> 6.1'
 end
````
>>
